const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Json,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Behaviors.scrollto,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Text,
		C3.Plugins.List,
		C3.Behaviors.Orbit,
		C3.Plugins.Particles,
		C3.Behaviors.Anchor,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.ScriptsInEvents.Es_main_menu_Event2_Act1,
		C3.Plugins.TiledBg.Cnds.IsOnScreen,
		C3.Plugins.List.Acts.SetVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.TiledBg.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.TiledBg.Cnds.OnCreated,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.List.Cnds.OnCreated,
		C3.Plugins.List.Acts.Select,
		C3.Plugins.List.Cnds.IsOnScreen,
		C3.Plugins.List.Exps.SelectedIndex,
		C3.Plugins.List.Cnds.CompareSelection,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.AdvancedRandom.Acts.CreatePermutationTable,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.AdvancedRandom.Exps.Permutation,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Text.Cnds.OnTypewriterTextFinished,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Acts.SetAngle
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{Touch: 0},
	{JSON: 0},
	{Keyboard: 0},
	{Audio: 0},
	{arr_save: 0},
	{pop_time: 0},
	{buttonSound: 0},
	{obj_button_return: 0},
	{fade_type: 0},
	{fade_time: 0},
	{destiny: 0},
	{Tween: 0},
	{Fade: 0},
	{Sine: 0},
	{loadingLogo: 0},
	{ScrollTo: 0},
	{obj_camera: 0},
	{start_game: 0},
	{current_quest: 0},
	{can_play: 0},
	{correct_number: 0},
	{title_question: 0},
	{obj_game_manager: 0},
	{anim_tofu: 0},
	{AdvancedRandom: 0},
	{random: 0},
	{button_answers: 0},
	{txt_answers: 0},
	{posX: 0},
	{posY: 0},
	{obj_animals: 0},
	{button_play: 0},
	{txt_language_title: 0},
	{List: 0},
	{Orbit: 0},
	{Background: 0},
	{obj_title: 0},
	{home: 0},
	{obj_title_background: 0},
	{txt_title: 0},
	{obj_notes: 0},
	{txt_result: 0},
	{txt_result_number: 0},
	{Particles: 0},
	{text_loading: 0},
	{Anchor: 0},
	{fam_hud_buttons: 0},
	{fam_interactive_buttons: 0},
	{Loaded: 0},
	{value: 0},
	{Fading: 0},
	{fadeTime: 0},
	{sound_off: 0},
	{language: 0},
	{current_selected: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	arr_save: class extends self.IArrayInstance {},
	buttonSound: class extends self.ISpriteInstance {},
	obj_button_return: class extends self.ISpriteInstance {},
	Fade: class extends self.ITiledBackgroundInstance {},
	loadingLogo: class extends self.ISpriteInstance {},
	obj_camera: class extends self.ISpriteInstance {},
	obj_game_manager: class extends self.ISpriteInstance {},
	anim_tofu: class extends self.ISpriteInstance {},
	AdvancedRandom: class extends self.IInstance {},
	button_answers: class extends self.ISpriteInstance {},
	txt_answers: class extends self.ITextInstance {},
	obj_animals: class extends self.ISpriteInstance {},
	button_play: class extends self.ISpriteInstance {},
	txt_language_title: class extends self.ITextInstance {},
	List: class extends self.IListInstance {},
	Background: class extends self.ISpriteInstance {},
	obj_title: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	obj_title_background: class extends self.ISpriteInstance {},
	txt_title: class extends self.ITextInstance {},
	obj_notes: class extends self.ISpriteInstance {},
	txt_result: class extends self.ITextInstance {},
	txt_result_number: class extends self.ITextInstance {},
	Particles: class extends self.IParticlesInstance {},
	text_loading: class extends self.ITextInstance {},
	fam_hud_buttons: class extends self.ISpriteInstance {},
	fam_interactive_buttons: class extends self.ISpriteInstance {}
}